apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fileshare
spec:
  rules:
  - host: student01.k8s.slurm.io
    http:
      paths:
      - backend:
          serviceName: fileshare
          servicePort: 80
