apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fileshare.fullname" . }}
  labels:
    app: {{ template "fileshare.name" . }}
    chart: {{ template "fileshare.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  default.conf: |
    server {
      listen       80 default_server;
      server_name  _;

      location / {
        return 200 '$hostname\n';
      }

      location /files {
        alias /data;
        autoindex on;
        client_body_temp_path /tmp;
        dav_methods PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access user:rw group:rw all:r;
      }
    }
