ceph_origin: repository
ceph_repository: community
ceph_repository_type: cdn
ceph_stable_release: luminous
public_network: "172.20.100.0/24"
cluster_network: "172.20.100.0/24"

osd_objectstore: bluestore
osd_scenario: collocated
devices:
  - /dev/sdb

osd_pool_default_pg_num: 30

ceph_conf_overrides:
  global:
    "osd journal size": 1024
    "osd pool default size": 3
    "osd pool default min size":  2
