apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: my-replicaset-2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.13
        name: nginx
        ports:
        - containerPort: 80
